### ISSUE TITLE
[1.20.1] Crash while attempting to generate world.

### ISSUE THREAD

**Issue by Gbergz** [Alexthw46/Eidolon-Repraised#10]
Title^

**Info**:
Client crash while attempting to generate a world.

**Versions:**
MC: 1.20.1
Eidolon: 0.3.5.7
Curious API: 5.3.5

**Crash-Report**: https://gist.githubusercontent.com/Gbergz/a4ac24c7a20f41ee199e97ab5e11f25c/raw/4b8bcc61bdedc41b189278c2f0605464ba365296/gistfile1.txt

**-** Gbergz

**Comment by Alexthw46** [comment]
Try this? (might take few mins to show up)
https://legacy.curseforge.com/minecraft/mc-mods/eidolon-repraised/files/4809313

**Comment by Gbergz** [comment]
Will do once I am available!

**Comment by Gbergz** [comment]
Seems to be working fine now, I'll report again if anything comes up. Thanks!
