### ISSUE TITLE
Bug and crash with Ars Ecclesia

### ISSUE THREAD

**Issue by Leinad112** [Alexthw46/Eidolon-Repraised#13]
MC Version: 1.20.1
Forge Version: 47.2.0
Mod Version: 0.3.5.7.1

When looking at any section of the Ars Ecclesia and using the mouse scrolling, the pages change but aren't syncrhonized, displaying the information incorrectly. There's some examples.

![imagen_2023-10-22_000407717](https://github.com/Alexthw46/Eidolon-Repraised/assets/88640725/cc20e0e4-c2ae-43a1-afe6-dededfbebda1)
![imagen_2023-10-22_000454609](https://github.com/Alexthw46/Eidolon-Repraised/assets/88640725/cd431b64-2117-495e-b3f4-961a7a3ba384)

Following the second image, if you scroll one time and return with a click, a crash occurs. This is the log.
[crash-2023-10-22_00.11.49-client.txt](https://github.com/Alexthw46/Eidolon-Repraised/files/13062490/crash-2023-10-22_00.11.49-client.txt)

**Comment by Alexthw46** [comment]
oh, you were not supposed to be able to scroll in a page like that. Will adjust the checks

**Comment by DonorKrovi** [comment]
https://mclo.gs/cHRG9k9

I think I have something like that?
