### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by DonorKrovi** [Alexthw46/Eidolon-Repraised#14]
https://mclo.gs/ua2IWxK

**Comment by Alexthw46** [comment]
Which version are you using? A fix to a similar bug was uploaded yesterday

**Comment by DonorKrovi** [comment]
> Which version are you using? A fix to a similar bug was uploaded yesterday

![image](https://github.com/Alexthw46/Eidolon-Repraised/assets/60231586/ba2f477e-982d-4582-a526-da2b96ff2804)

**Comment by DonorKrovi** [comment]
Try to assemble it?

**Comment by Alexthw46** [comment]
Def try to update it first (it's on curseforge now)

**Comment by DonorKrovi** [comment]
ok

**Comment by DonorKrovi** [comment]
https://mclo.gs/8mexooQ
I'm use lates version

**Comment by DonorKrovi** [comment]
![image](https://github.com/Alexthw46/Eidolon-Repraised/assets/60231586/359ec75e-521f-48bb-8df7-4a9935c1a36f)

**Comment by SiverDX** [comment]
https://github.com/Alexthw46/Eidolon-Repraised/blob/dbd4d09816b71fd0b3e15f0c265458f55a2d82a0/src/main/java/elucent/eidolon/common/block/CrucibleBlock.java#L50

might need to use setLevel (if that exists) or pass the level as a parameter for the sync method

**Comment by Alexthw46** [comment]
no, the problem is that the method is called when the tile entity doesn't have a level yet, as jt's trying to generate it into a structure. It's simply missing a null check, the level will be assigned shortly after and everything should update later.

**Comment by SiverDX** [comment]
will the sync even happen if you exit it at that point
like does it call that method again or the sync at some other point

**Comment by Alexthw46** [comment]
there won't be nothing to sync if the block entity is not yet initialized. When something changes, it will call sync again.

**Comment by DonorKrovi** [comment]
Let me know when the test is available.

**Comment by Alexthw46** [comment]
Need to work a bit on a thing before release, but if you want to test it 
[eidolon_repraised-1.19.2-0.3.5.8.zip](https://github.com/Alexthw46/Eidolon-Repraised/files/13064059/eidolon_repraised-1.19.2-0.3.5.8.zip)

**Comment by DonorKrovi** [comment]
> Нужно немного поработать над вещью перед релизом, но если вы хотите протестировать ее [eidolon_repraised-1.19.2-0.3.5.8.zip](https://github.com/Alexthw46/Eidolon-Repraised/files/13064059/eidolon_repraised-1.19.2-0.3.5.8.zip)

this is 1.19.2 my version 1.20.1 :-)

**Comment by Alexthw46** [comment]
this is why my brain doesn't like to work on both versions at the same time
[eidolon_repraised-1.20.1-0.3.5.8.zip](https://github.com/Alexthw46/Eidolon-Repraised/files/13064389/eidolon_repraised-1.20.1-0.3.5.8.zip)

**Comment by DonorKrovi** [comment]
> Вот почему мой мозг не любит работать над обеими версиями одновременно [eidolon_repraised-1.20.1-0.3.5.8.zip](https://github.com/Alexthw46/Eidolon-Repraised/files/13064389/eidolon_repraised-1.20.1-0.3.5.8.zip)

I don't think you should pay attention to the old versions, if you concentrate all your efforts on one thing, your brain won't explode

**Comment by DonorKrovi** [comment]
Seem to be fixed
