### ISSUE TITLE
Altar automation

### ISSUE THREAD

**Issue by slava110** [Alexthw46/Eidolon-Repraised#15]
While chanting is cool, I think that altar would benefit from automation. Maybe some kind of custom noteblocks would be able to perform chants like player?

**Comment by Alexthw46** [comment]
Why do you think it would? Prayer chants have a long cooldown and does not makes sense to delegate a prayer to a machine.
The other types of chant also consume mana, which is an important detail. But first of all, what's the main use case to that?

On another hand, I'll add parchments, at some point, that can trigger a previously inscribed chant to make spells like smite and enthrall easier to use on the go.

**Comment by slava110** [comment]
Sorry, I think you're right. In context of the mod it isn't that useful. I'm just making modpack related to automation. I'll try to implement them myself for my modpack then c:
