### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by DonorKrovi** [Alexthw46/Eidolon-Repraised#19]
https://mclo.gs/FvNAEno

**Comment by DonorKrovi** [comment]
![image](https://github.com/Alexthw46/Eidolon-Repraised/assets/60231586/c1661bbb-2950-447b-9316-f1b776213629)
i'm drop enchanted_ash and crash server

**Comment by DonorKrovi** [comment]
![image](https://github.com/Alexthw46/Eidolon-Repraised/assets/60231586/8c7ec272-db91-46ee-8eec-9b9fc4f9dc84)

**Comment by DonorKrovi** [comment]
It doesn't always work out on the first try

**Comment by Alexthw46** [comment]
Well that's one of the weirdest thing I saw reported, it's claiming a class from the mod itself is missing

**Comment by Alexthw46** [comment]
Can you manage to try without Neruina? It might still crash if that's not the resposible, but at least it should give a better report

**Comment by DonorKrovi** [comment]
> Сможете ли вы попробовать без Неруины? Он все еще может дать сбой, если это не является ответственным фактором, но, по крайней мере, он должен дать лучший отчет

ok, later

**Comment by DonorKrovi** [comment]
After restarting the server, I can no longer reproduce this, strange
and I didn't delete the neruina

**Comment by Alexthw46** [comment]
for all i know, maybe something went wrong with the loading of the mod. The only way i ever got those errors were by replacing the jar on the server while it was running (so the compiled code on ram was different from the one on disk). I'll leave it open for now but eventually close this if it was just a bad day for your server
