### ISSUE TITLE
[1.19.2]: Wand crashes server with Apotheosis installed

### ISSUE THREAD

**Issue by Parmesaaan** [Alexthw46/Eidolon-Repraised#22]
When right-clicking the Soulfire wand on a Minecraft server that has Apotheosis installed, the server crashes. It is important to note that I have the adventure module of Apotheosis (the one that adds affixes to items) disabled.

I suspect Eidolon checks if Apotheosis is installed when attempting to provide compatibility with affixes - but doesn't check to make sure the adventure module of Apotheosis is enabled or not. Just a suspicion, don't have much experience with game dev.

Have restarted server/client to test, and it's reproducible. I will test with only Eidolon: Repraised and Apotheosis installed, with and without the adventure module enabled, and post results.

Crash report: [https://mclo.gs/r4Jl9fz](https://mclo.gs/r4Jl9fz)

**Comment by SiverDX** [comment]
the problem in this case is the wrong Pair class being used
apparently i imported the wrong one

disabled module should be fine i think? in that case you simply wouldnt have any affixes on the item and the classes being used are still present even if its disabled (and those methods are used by apotheosis through mixins without any checks either)

**Comment by Alexthw46** [comment]
Hotfix should be released now
