### ISSUE TITLE
[SOLVED] Ritual of Enthralling not working

### ISSUE THREAD

**Issue by ryennce** [Alexthw46/Eidolon-Repraised#24]
eidolon_repraised-1.20.1-0.3.7.0 

The ritual:
![image](https://github.com/Alexthw46/Eidolon-Repraised/assets/102876250/17923922-82e6-4c1b-8459-7c597f939d9d)

The Setup: 
![image](https://github.com/Alexthw46/Eidolon-Repraised/assets/102876250/27f1f771-6d3d-4d63-a377-869791fd1e47)

The issue: 
![image](https://github.com/Alexthw46/Eidolon-Repraised/assets/102876250/dd1d2cb1-5519-4d33-8410-65ea8bade1c1)

Activating it only consumes the center piece and nothing happens, i have a skeleton nearby and nothing is happening

![image](https://github.com/Alexthw46/Eidolon-Repraised/assets/102876250/9e85389f-6fc8-4e1b-b26c-4402713ff96c)

**Comment by Alexthw46** [comment]
I need to add more information to the codex entry, and apparently the recipe viewer too. But it shouldn't be a game-mechanics bug

Two reasons why it doesn't work:
* Staff needs to be on a necrotic focus (which is why it fails fast)
* Mobs need to be under 1/3 of their max health

**Comment by ryennce** [comment]
Seems like that was the problem. "Tamed" a Wither susessfully.
(he keeps trying to atack me but does not damage me, only other mobs)

**Comment by Alexthw46** [comment]
Yeah, wither has like 3 brains. You can manage to tame one but the other two have other rules that would need pretty invasive code
