### ISSUE TITLE
Eidolon Failed to load with latest Placebo update

### ISSUE THREAD

**Issue by ArcaneSan** [Alexthw46/Eidolon-Repraised#25]
Failure message: Eidolon:Repraised (eidolon) has failed to load correctly
		java.lang.AbstractMethodError: Receiver class dev.shadowsoffire.apotheosis.adventure.affix.AffixRegistry does not define or inherit an implementation of the resolved method 'abstract void registerBuiltinCodecs()' of abstract class dev.shadowsoffire.placebo.reload.DynamicRegistry.

Updating Placebo causes this failure message for Eidolon: Repraised. I know the update was today, so I wanted to bring this to your attention as a way to help

Associated Crash report

[crash-2023-11-16_06.53.52-fml.txt](https://github.com/Alexthw46/Eidolon-Repraised/files/13379155/crash-2023-11-16_06.53.52-fml.txt)

**Comment by SiverDX** [comment]
i dont think the current apotheosis version is compatible with the latest placebo update
try launching without eidolon

**Comment by ArcaneSan** [comment]
You know, I never considered that since that group of mods is all made by the same person, It works without apoth weirdly, but I'll close it, just strange that mc announces that Eidolon failed

**Comment by Alexthw46** [comment]
Likely to be a problem soon anyway. Just delayed to when Apoth updates

**Comment by SiverDX** [comment]
so far only this i think:

serializer stuff is removed

```java
public static final PSerializer<HailingAffix> SERIALIZER = PSerializer.fromCodec("Hailing Affix", CODEC);

@Override
public PSerializer<? extends Affix> getSerializer() {
    return SERIALIZER;
}
```

and replaced with codec

```java
@Override
public Codec<? extends Affix> getCodec() {
    return CODEC;
}
```

and register looks like this

```java
AffixRegistry.INSTANCE.registerCodec(new ResourceLocation(Eidolon.MODID, "hailing"), HailingAffix.CODEC);
```

**Comment by ArcaneSan** [comment]
As mentioned, it is indeed an issue when apoth updated. So I'll contribute the crash log to help

[crash-2023-11-17_07.32.50-fml.txt](https://github.com/Alexthw46/Eidolon-Repraised/files/13393733/crash-2023-11-17_07.32.50-fml.txt)

**Comment by ArcaneSan** [comment]
Latest version was able to start alongside the latest placebo and such, thanks!
