### ISSUE TITLE
Crash when crafting Custom Recipe in Worktable that has remainder items

### ISSUE THREAD

**Issue by oitsjustjose** [Alexthw46/Eidolon-Repraised#29]
**Game Version:** 1.20.1

**Version:** 0.3.7.3

**Description:**

Heya! Was adding in a custom recipe (shown below) and when I crafted it to test things, I immediately received a crash. Replacing the Water Bucket in the recipe with another item that isn't a ContainerItem for crafting, I could no longer repro the crash.

Recipe:

```json
{
  "type": "eidolon:worktable",
  "pattern": [
    "gwg",
    "whw",
    "gwg"
  ],
  "reagents": "gggg",
  "key": {
    "g": {
      "item": "minecraft:glowstone"
    },
    "h": {
      "item": "eidolon:holy_symbol"
    },
    "w": {
      "item": "minecraft:water_bucket"
    }
  },
  "result": {
    "item": "aether:aether_portal_frame"
  }
}
```

[Crash Report](https://gist.github.com/oitsjustjose/83522eea2ca84d6bc39af904c9aa9152)

<details>
<summary><b>Mod List</b></summary>
<ul>
<li>adv_nuker-1.20-1.3.jar</li>
<li>ae2qolrecipes-neoforge-1.20.1-1.1.1.jar</li>
<li>ae2wtlib-15.1.3-forge.jar</li>
<li>aecapfix-0.6.jar</li>
<li>AEInfinityBooster-1.20.1-1.0.0+20.jar</li>
<li>aeroblender-1.20.1-1.0.1-neoforge.jar</li>
<li>aether-1.20.1-1.0.0-beta.1.4-neoforge.jar</li>
<li>aether-redux-1.3.3-1.20.1-neoforge.jar</li>
<li>almostunified-forge-1.20.1-0.7.2.jar</li>
<li>alternate_current-mc1.20-1.7.0.jar</li>
<li>appleskin-forge-mc1.20.1-2.5.1.jar</li>
<li>Applied-Mekanistics-1.4.2.jar</li>
<li>appliedenergistics2-forge-15.0.15.jar</li>
<li>architectury-9.1.12-forge.jar</li>
<li>backpacked-forge-1.20.1-2.2.5.jar</li>
<li>BadMobs-1.20.1-19.0.2.jar</li>
<li>balm-forge-1.20.1-7.1.4.jar</li>
<li>bellsandwhistles-0.4.3-1.20.x.jar</li>
<li>bloodmagic-1.20.1-3.3.2-44.jar</li>
<li>Bookshelf-Forge-1.20.1-20.1.6.jar</li>
<li>brazier-forge-6.1.1.jar</li>
<li>buildinggadgets2-1.0.6.jar</li>
<li>caelus-forge-3.1.0+1.20.jar</li>
<li>cagedmobs-1.20.1-2.0.1.jar</li>
<li>catalogue-forge-1.20.1-1.8.0.jar</li>
<li>cfm-forge-1.20.1-7.0.0-pre36.jar</li>
<li>chunkloaders-1.2.8a-forge-mc1.20.1.jar</li>
<li>citresewn-1.20.1-5.jar</li>
<li>cloth-config-12.0.109-forge.jar</li>
<li>ColdSweat-2.2.2.jar</li>
<li>collective-1.20.1-7.7.jar</li>
<li>ColossalChests-1.20.1-1.8.4.jar</li>
<li>comforts-forge-6.3.4+1.20.1.jar</li>
<li>compressedcreativity-1.20.1-0.1.8.b.jar</li>
<li>connectedglass-1.1.9-forge-mc1.20.1.jar</li>
<li>Controlling-forge-1.20.1-12.0.2.jar</li>
<li>corpse-1.20.1-1.0.5.jar</li>
<li>crawlondemand-1.20.x-1.0.0.jar</li>
<li>create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.7.g.jar</li>
<li>create_power_loader-1.2.0-mc1.20.1.jar</li>
<li>create-1.20.1-0.5.1.f.jar</li>
<li>creeperoverhaul-3.0.1-forge.jar</li>
<li>ctov-3.3.6.jar</li>
<li>ctov-farmers-delight-compat-2.1.jar</li>
<li>ctov-immersive-engineering-compat-2.0.jar</li>
<li>ctov-pneumaticcraft-compat-1.0.jar</li>
<li>cupboard-1.20.1-2.1.jar</li>
<li>curios-forge-5.4.2+1.20.1.jar</li>
<li>CyclopsCore-1.20.1-1.18.13.jar</li>
<li>DarkPaintings-Forge-1.20.1-17.0.4.jar</li>
<li>Decorative Blocks-forge-1.20.1-4.0.2.jar</li>
<li>deep_aether-1.20.1-1.0.12.jar</li>
<li>Delightful-1.20.1-3.4.2.jar</li>
<li>DiagonalFences-v8.1.2-1.20.1-Forge.jar</li>
<li>Difficult Caves 1.0.0 - 1.20.1.jar</li>
<li>DimStorage-1.20.1-8.0.1.jar</li>
<li>doubledoors-1.20.1-5.1.jar</li>
<li>DrawersTooltip-1.20.1-forge-8.0.0.jar</li>
<li>dungeons-and-taverns-3.0.3 [Forge].jar</li>
<li>EasyAnvils-v8.0.1-1.20.1-Forge.jar</li>
<li>eatinganimation-1.20-5.0.0.jar</li>
<li>ecologics-forge-1.20.1-2.2.0.jar</li>
<li>EdivadLib-1.20.1-2.0.1.jar</li>
<li>eidolon_repraised-1.20.1-0.3.7.3.jar</li>
<li>elytraslot-forge-6.3.0+1.20.1.jar</li>
<li>embeddium-0.2.9+mc1.20.1.jar</li>
<li>embeddiumplus-1.20.1-v1.0.1.jar</li>
<li>embersrekindled-1.20.1-1.0.2.jar</li>
<li>EnderIO-1.20.1-6.0.21-alpha.jar</li>
<li>endermanoverhaul-forge-1.20.1-1.0.1.jar</li>
<li>enlightend-5.0.14-1.20.1.jar</li>
<li>entangled-1.3.16-forge-mc1.20.jar</li>
<li>entity_model_features_forge_1.20-1.0.2.jar</li>
<li>entity_texture_features_forge_1.20-4.5.1.jar</li>
<li>everycomp-1.20-2.6.17.jar</li>
<li>expandedstorage-10.0.0-beta.3+1.20-forge.jar</li>
<li>explorify-v1.3.0-mc1.20.jar</li>
<li>extremesoundmuffler-3.41-forge-1.20.jar</li>
<li>FarmersDelight-1.20.1-1.2.3.jar</li>
<li>Fastload-Reforged-mc1.20.1-3.4.0.jar</li>
<li>fastpaintings-1.20-1.2.1.jar</li>
<li>FastSuite-1.20.1-5.0.1.jar</li>
<li>ferritecore-6.0.1-forge.jar</li>
<li>foglooksmodernnow-1.1.0.jar</li>
<li>FramedBlocks-9.1.6.jar</li>
<li>framedcompactdrawers-1.20-6.0.0.jar</li>
<li>framework-forge-1.20.1-0.6.16.jar</li>
<li>fusion-1.1.0b-forge-mc1.20.1.jar</li>
<li>geckolib-neoforge-1.20.1-4.2.4.jar</li>
<li>Guide-API-VP-1.20.1-2.2.6.jar</li>
<li>handcrafted-forge-1.20.1-3.0.5.jar</li>
<li>heracles-forge-1.20.1-1.1.4.jar</li>
<li>Highlighter-1.20.1-forge-1.1.7.jar</li>
<li>Iceberg-1.20.1-forge-1.1.16.jar</li>
<li>ImmediatelyFast-1.2.7+1.20.2.jar</li>
<li>ImmersiveEngineering-1.20.1-10.0.0-169.jar</li>
<li>infwithmend-forge-1.20.x-1.0.2.jar</li>
<li>interiors-0.5.2+mc1.20.1-FORGE.jar</li>
<li>InventoryProfilesNext-forge-1.20-1.10.9.jar</li>
<li>Jade-1.20.1-forge-11.6.3.jar</li>
<li>JadeAddons-1.20.1-forge-5.2.1.jar</li>
<li>jei-1.20.1-forge-15.2.0.27.jar</li>
<li>JustEnoughMekanismMultiblocks-1.20.1-4.2.jar</li>
<li>Kiwi-1.20.1-forge-11.1.1.jar</li>
<li>kleeslabs-forge-1.20-15.0.0.jar</li>
<li>KubeJS Blood Magic-1.0.0-1.20.1.jar</li>
<li>kubejs_enderio-forge-1.20.1-0.4.1.jar</li>
<li>kubejs-create-forge-2001.2.5-build.2.jar</li>
<li>kubejs-forge-2001.6.4-build.95.jar</li>
<li>labels-1.20-1.16.jar</li>
<li>laserio-1.6.7.jar</li>
<li>libIPN-forge-1.20-4.0.1.jar</li>
<li>lootjs-forge-1.20.1-2.10.3.jar</li>
<li>lootr-1.20-0.7.30.73.jar</li>
<li>make_bubbles_pop-0.2.0-forge-mc1.19.4+.jar</li>
<li>map_atlases-1.20-5.12.0-all.jar</li>
<li>mcjtylib-1.20-8.0.3.jar</li>
<li>mcw-bridges-2.1.1-mc1.20.1forge.jar</li>
<li>mcw-paintings-1.0.5-1.20.1forge.jar</li>
<li>Mekanism-1.20.1-10.4.5.19.jar</li>
<li>MekanismGenerators-1.20.1-10.4.5.19.jar</li>
<li>MekanismWeapons-1.20.1-1.2.jar</li>
<li>merequester-forge-1.20.1-1.1.4.jar</li>
<li>mininggadgets-1.15.6.jar</li>
<li>modelfix-1.14.jar</li>
<li>modernfix-forge-5.9.3+mc1.20.1.jar</li>
<li>modular-routers-12.0.2+mc1.20.1.jar</li>
<li>moonlight-1.20-2.8.65-forge.jar</li>
<li>more-immersive-wires-1.20.1-1.1.2.jar</li>
<li>moreoverlays-1.22.1-mc1.20.jar</li>
<li>MouseTweaks-forge-mc1.20-2.25.jar</li>
<li>movingelevators-1.4.5-forge-mc1.20.1.jar</li>
<li>mvs-4.1.1-1.20-forge.jar</li>
<li>naturalist-forge-4.0.3-1.20.1.jar</li>
<li>netherportalfix-forge-1.20-13.0.0.jar</li>
<li>nethersdelight-1.20.1-4.0.jar</li>
<li>no-f3-1.jar</li>
<li>obsidianui-0.1.2+1.20.1.jar</li>
<li>Patchouli-1.20.1-81-FORGE.jar</li>
<li>Placebo-1.20.1-8.5.8.jar</li>
<li>pneumaticcraft-repressurized-6.0.11+mc1.20.1.jar</li>
<li>Powah-5.0.4.jar</li>
<li>PrettyPipes-1.15.0-all.jar</li>
<li>probejs-5.5.0-forge.jar</li>
<li>PuzzlesLib-v8.1.9-1.20.1-Forge.jar</li>
<li>radium-mc1.20.1-0.12.2+git.5f80f74.jar</li>
<li>raised-forge-1.20.1-3.1.0.jar</li>
<li>rechiseled-1.1.5c-forge-mc1.20.jar</li>
<li>RegionsUnexploredForge-0.5.3+1.20.1.jar</li>
<li>resourcefulconfig-forge-1.20.1-2.1.0.jar</li>
<li>resourcefullib-forge-1.20.1-2.1.16.jar</li>
<li>rftoolsbase-1.20-5.0.2.jar</li>
<li>rftoolspower-1.20-6.0.1.jar</li>
<li>rftoolsstorage-1.20-5.0.1.jar</li>
<li>rhino-forge-2001.2.2-build.13.jar</li>
<li>riverredux-0.3.1.jar</li>
<li>Ryoamiclights-0.1.5+1.20.1.jar</li>
<li>Searchables-forge-1.20.1-1.0.2.jar</li>
<li>SereneSeasons-1.20.1-9.0.0.46.jar</li>
<li>SnowRealMagic-1.20.1-forge-9.0.2.jar</li>
<li>spark-1.10.53-forge.jar</li>
<li>spawn-1.0.2-forge.jar</li>
<li>specialised_cells-1.0.0.jar</li>
<li>Steam_Rails-1.5.3+forge-mc1.20.1.jar</li>
<li>storagedrawers-1.20.1-12.0.2.jar</li>
<li>Structory_1.20.2_v1.3.3.jar</li>
<li>structureessentials-1.20.1-3.2.jar</li>
<li>subterrestrial-forge-1.20-2.2.0.jar</li>
<li>supermartijn642configlib-1.1.8-forge-mc1.20.jar</li>
<li>supermartijn642corelib-1.1.15-forge-mc1.20.jar</li>
<li>supplementaries-1.20-2.6.31.jar</li>
<li>tectonic-mod-mc1.19.3+-v2.1.1.jar</li>
<li>TerraBlender-forge-1.20.1-3.0.0.169.jar</li>
<li>textrues_embeddium_options-0.1.3+mc1.20.1.jar</li>
<li>trashcans-1.0.18b-forge-mc1.20.jar</li>
<li>trashslot-forge-1.20-15.1.0.jar</li>
<li>TravelersTitles-1.20-Forge-4.0.1.jar</li>
<li>TreeChop-1.20.1-forge-0.18.3.jar</li>
<li>twigs-1.20.1-3.1.0-forge.jar</li>
<li>visuality-forge-2.0.2.jar</li>
<li>VTweaks-1.20.1-4.0.12.jar</li>
<li>Wabi-Sabi-Structures-2.0.0-1.20-Forge.jar</li>
<li>waystones-forge-1.20-14.0.2.jar</li>
<li>WI-Zoom-1.5-MC1.20.1-Forge.jar</li>
<li>wits-1.1.0+1.20.1-forge.jar</li>
<li>xnet-1.20-6.0.2.jar</li>
<li>xnetgases-1.20.1-5.0.0.jar</li>
<li>YungsApi-1.20-Forge-4.0.2.jar</li>
<li>YungsBetterDesertTemples-1.20-Forge-3.0.3.jar</li>
<li>YungsBetterDungeons-1.20-Forge-4.0.3.jar</li>
<li>YungsBetterEndIsland-1.20-Forge-2.0.4.jar</li>
<li>YungsBetterJungleTemples-1.20-Forge-2.0.4.jar</li>
<li>YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar</li>
<li>YungsBetterStrongholds-1.20-Forge-4.0.3.jar</li>
</ul>
</details>

**Comment by Alexthw46** [comment]
Just tried (same recipe, a dirt block instead of the aether) and no issue. So weird stuff that doesn't always crash? Hard to debug this kind sadly

**Comment by Alexthw46** [comment]
The holy/unholy symbols themselves are "remainder items" so it shouldn't be a generic issue

**Comment by Alexthw46** [comment]
new update should fix this, i haven't been able to reproduce it but i've set guards to avoid the crash in theory
