### ISSUE TITLE
Server crashing after Dark Prayer

### ISSUE THREAD

**Issue by Venngale** [Alexthw46/Eidolon-Repraised#3]
Playing on multiplayer server on 1.19.2, server crashes inconsistently when performing the dark prayer, appeared to start after reaching a particular threshhold of reputation with deity. 

[crash-2023-08-13_17.52.03-server.txt](https://github.com/Alexthw46/Eidolon-Repraised/files/12330829/crash-2023-08-13_17.52.03-server.txt)
[crash-2023-08-13_16.24.12-server.txt](https://github.com/Alexthw46/Eidolon-Repraised/files/12330831/crash-2023-08-13_16.24.12-server.txt)
[crash-2023-08-13_16.01.41-server.txt](https://github.com/Alexthw46/Eidolon-Repraised/files/12330832/crash-2023-08-13_16.01.41-server.txt)

**Comment by Venngale** [comment]
Crashed again following attempt to zombify villager. https://mclo.gs/QpVZQzK

**Comment by Alexthw46** [comment]
I should have fixed that in last git release, and obv in the more recent curseforge one. I'm closing this but let me now if it happens again with the new jars
