### ISSUE TITLE
Two Advancements not detecting / working

### ISSUE THREAD

**Issue by Dragnier** [Alexthw46/Eidolon-Repraised#31]
I have done sacrifice villager several times now without the advancement detecting. ~~Similarly, I've cured a zombie villager with the ritual of purifying without that advancement detecting.~~

Also, I've done both researches (winter and fire) and those advancements did not complete either.

**Comment by Alexthw46** [comment]
While the cure zombie thing needs to be done via chant to trigger the advancement, the sacrifice villager thing was totally a bug caused by a typo. I looked everywhere for the cause but the problem was that simple ç _ ç
