### ISSUE TITLE
Crash when praying with the goblet

### ISSUE THREAD

**Issue by YourCatIsGay** [Alexthw46/Eidolon-Repraised#32]
Every time I try to prey (2 wicked sign + 1 blood sign) the game crash and now i have these symbol on my screen whatever i do. 

The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.EntityType.m_20615_(net.minecraft.world.level.Level)" because the return value of "elucent.eidolon.common.tile.GobletTileEntity.getEntityType()" is null

**Comment by Alexthw46** [comment]
should be solved when curse approves this
