### ISSUE TITLE
Wood type may not be registered correctly?

### ISSUE THREAD

**Issue by katubug** [Alexthw46/Eidolon-Repraised#35]
Hi! I'm troubleshooting some resource generation issues, and so I'm addressing a part of my latest.log which has to do with that.

Here's the pastebin link: https://pastebin.com/DxTqJaRN

Supplementaries fails to generate a hanging sign texture for Illwood and suggests the wood type might be registered incorrectly. I have no idea what that means, but MehVahdJukaar said I should report it, so here I am!

**Versions**
 - Eidolon: 0.3.7.5
 - Forge: 47.2.17

**Comment by Alexthw46** [comment]
if it's just the hanging sign, no worries, it should be implemented soon natively, all i can read from the log is that it's searching for its texture that obv isn't present
