### ISSUE TITLE
[1.20.1] Raven Cloak crashes when used in multiplayer

### ISSUE THREAD

**Issue by Visual-Anxiety** [Alexthw46/Eidolon-Repraised#37]
I am using the Raven Cloak in a multiplayer server with a large modpack using Forge version 47.2.14, and when I use the cloak such that the number of jumps goes from 10 to 9, I get the following crash:

`Internal Exception: Java.land.IndexOutOfBoundsException: readerIndex(17) + length(8) exceeds writerIndex(12): PooledUnsafeDirectByteBuf(ridx: 17, widx: 17, cap: 17)`

Error is not replicated in a singleplayer world using the same modpack.

Edit: Upon further investigation and testing, it only crashes when the bar for the raven cloak reaches maximum power (reaches the orange colored section).

Image provided below showing the crash screen, in case I mistyped it above.
![RavenCloakCrash](https://github.com/Alexthw46/Eidolon-Repraised/assets/155265708/9a90fc69-6c63-4db6-a543-89213cd6c1d2)

**Comment by katubug** [comment]
I'm not the developer, but since I am here I will let you know it would be really helpful if you could include the actual crash report as well! It's found in your Minecraft directory under /crash-reports/
