### ISSUE TITLE
[1.20.1] Game crashes when use Deathbringer's Scythe attack piglin Alchemist from Piglin Proliferation mod

### ISSUE THREAD

**Issue by sorataxi** [Alexthw46/Eidolon-Repraised#40]
When my freind used the Deathbringer`s Scythe  attack the piglin Alchemist in multiplayer game, it caused the server to crash. then after a little  singleplay test,I think probably is the "undead" potion effect caused the game crash ,because it also happened when I use the "undead" potion only to the piglin Alchemist. Here is the crash report."
[crash-2024-01-07_04.59.17-server.txt](https://github.com/Alexthw46/Eidolon-Repraised/files/13851424/crash-2024-01-07_04.59.17-server.txt)

**Comment by Alexthw46** [comment]
Sorry if the bugfix is taking long to go live but my schedule is messed up due to exam projects with deadlines and i need to manage to fix a few more bugs before releasing. As the little message above implies, it was just a little sneaky porting error and fixed in-dev
