### ISSUE TITLE
CTD upon drinking extended potion of undeath.

### ISSUE THREAD

**Issue by pieflea** [Alexthw46/Eidolon-Repraised#41]
Was playing in ATM9 trying to pull off a lich bit, figured this potion was key... however, drinking the eight minute potion causes a crash to desktop, strangely, the splash potion does not cause this effect, may be related to another mod, however, worth reporting.

**Comment by Alexthw46** [comment]
i was going to say "try to update" but i havent't release the fix for it yet sadly. it's a confirmed bug and fixed indev already

**Comment by Alexthw46** [comment]
should be released now

**Comment by pieflea** [comment]
Nice glad to hear it! Loving the mod by the way!
    On Thursday, January 25, 2024 at 09:22:46 AM PST, Alexthw ***@***.***> wrote:  
 
 


should be released now
