### ISSUE TITLE
[Suggestion] Config options / datapacks for Prayers

### ISSUE THREAD

**Issue by oitsjustjose** [Alexthw46/Eidolon-Repraised#47]
Heyo! I've asked about this topic before, but as my pack nears release I've run into a lot of complaints from others about the amount of time it takes between successful chants to the Effigy (i.e. Dark Prayer). Is there any chance you can add either (1) DataPack support for each of these so the type of chant and cool-down can be configured, or (2, much easier) a global modifier to the time that can be controlled by a common/server config?

**Comment by Alexthw46** [comment]
Per-chant configs added with 3.8.8
