### ISSUE TITLE
[Neoforge 46.1.76 ] Entity Page Crash with ImmediatelyFast

### ISSUE THREAD

**Issue by spunchbop121** [Alexthw46/Eidolon-Repraised#5]
https://pastebin.com/xMZ2BTLe latest.log
https://pastebin.com/4dm8ExAA crash report

Game crashes after I clicked on the "monsters" tab from the codex book

**Comment by SiverDX** [comment]
https://github.com/Alexthw46/Eidolon-Repraised/blob/180103ad3c8b40274d1e5c285fe9e4d8c665bf10/src/main/java/elucent/eidolon/codex/EntityPage.java#L38

seems to be missing something like this:
`bufferbuilder.begin(Mode.QUADS, DefaultVertexFormat.POSITION_COLOR);` (from `tess.getBuilder()`)

though I don't know which mode should be used here

**Comment by Alexthw46** [comment]
Since the bufferbuilder begin was never needed and the page worked during the tests on our server pack, i guess this is tied to another mod. Fault can still be on me, just need to dig deeper

**Comment by Alexthw46** [comment]
In fact, seems to only appear with ImmediatlyFast loaded. Not sure on what's the deal with it.

https://github.com/RaphiMC/ImmediatelyFast/issues/125

**Comment by SiverDX** [comment]
replace the tesselator with `MultiBufferSource.BufferSource bufferSource = Minecraft.getInstance().renderBuffers().bufferSource();` and `bufferSource.endBatch()`

no immediatelyfast:
![image](https://github.com/Alexthw46/Eidolon-Repraised/assets/22003703/d108b195-29f3-4962-8e26-1f8f5f3ddb7f)

immediatelyfast:
![image](https://github.com/Alexthw46/Eidolon-Repraised/assets/22003703/13028372-a3da-46da-bb0b-a61455ac6a5b)

**Comment by SiverDX** [comment]
this is also relevant for 1.19.2 btw

**Comment by Alexthw46** [comment]
merge conflicts, can't port that instantly like the other ones

**Comment by Alexthw46** [comment]
Alr, check the new jar https://legacy.curseforge.com/minecraft/mc-mods/eidolon-repraised/files
