### ISSUE TITLE
Music disc not playing

### ISSUE THREAD

**Issue by Emery319** [Alexthw46/Eidolon-Repraised#50]
NeoForge: 47.1.96
Eidolon Repraised: 1.20.1-0.3.8.1
Curios API: 5.5.0+1.20.1

The music disc only plays for about a second and then stops.
![2024-02-23_17 19 11](https://github.com/Alexthw46/Eidolon-Repraised/assets/124550540/76cb761d-dbfd-4390-a752-8713ffec6cb5)

**Comment by Gronglegrowth** [comment]
I experience this too. Why did you close this? Did you find a cause and not say it?

**Comment by Emery319** [comment]
> I experience this too. Why did you close this? Did you find a cause and not say it?

I submitted a pull request and it's been merged by the author, so this bug will be fixed in the next update, I apologize if this confuses you!

**Comment by Emery319** [comment]
This is caused by not setting the disc's playing tick correctly when updating to 1.20.1.

https://github.com/Alexthw46/Eidolon-Repraised/pull/51
