### ISSUE TITLE
Suggestion: athame harvest for white flowers to look at a forge tagged white flower? 

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [Alexthw46/Eidolon-Repraised#52]
NeoForge: 47.2.20
Eidolon Repraised: 1.20.1-0.3.8.1
Curios API: 5.7.0+1.20.1

The athame doesn't seem to recognize modded white flowers from Meadow or Verdant Vibes to break for the special plant drops. Is it vanilla only?

**Comment by katubug** [comment]
Hi, wanted to chime in to this as well. I couldn't find anything in the mod jar that suggested white flowers were data-driven, which would allow me as a modpack author to add support for custom flowers. Did I miss something? Thanks for your time!
