### ISSUE TITLE
Crucible not working

### ISSUE THREAD

**Issue by Legorfyr** [Alexthw46/Eidolon-Repraised#59]
I'm playing TNP LLS7 v1.10 with eidolon_repraised-1.20.1-0.3.8.8b

The Crucible from Eidolon refuses to take any ingredient to craft anything. The crucible is heated, has water and it's bubbling, yet items stay on the bottom of the cauldron and are not getting dissolved.

To Reproduce

    Netherrack, light it, place crucible on top, pour water in, wait for the bubbles.
    Throw in 2 redstone and a soul shard (first step to make arcane gold)
    Watch as the items stay in the cauldron, not getting dissolved.

**Comment by Alexthw46** [comment]
It's a confirmed bug that might have been fixed indev and I'll probably upload the hotfix asap. In the meanwhile, enabling the "turn based mode" in the config should work
