### ISSUE TITLE
Crash with Custom Ritual crafting (1.19.2)

### ISSUE THREAD

**Issue by Sir-Bobbing** [Alexthw46/Eidolon-Repraised#6]
I've not yet tested with 1.20 as that's not the target for my project. But I've found that creating custom crafting rituals result in a crash.

The resulting error is as follows:
> java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because the return value of "elucent.eidolon.api.ritual.Ritual.getRegistryName()" is null

**Comment by Alexthw46** [comment]
If you mean by testing the add/editing of recipes, can you also share the Json? 

Otherwise clarify what you meant for custom ritual

**Comment by Sir-Bobbing** [comment]
Correction:

It's Ritual item crafting in general. I had a feeling to double check with the sanguine amulet recipe and same result

(should've tested that yesterday)

**Comment by Alexthw46** [comment]
Oh, found the issue you mention

**Comment by Alexthw46** [comment]
5.7 solves this
