### ISSUE TITLE
Bug >> Internal exception: io.netty.handler... Kicking Everyone From Server >> capabilities.dat

### ISSUE THREAD

**Issue by KakashoLin** [Alexthw46/Eidolon-Repraised#60]
Since the latest update, there has been an issue where anyone joining will get auto kicked with the following message "internal exception: io.netty.handler index 26 out of bounds for length 5". 

After a few days of digging, our server found it was an entry under capabilities.dat for Eidolon-Repraised was causing the error. Once you removed the entry for the entire mod under capabilities.dat, then the error went away and people could join again.

File at issue: capabilities.dat
Minecraft Version: 1.20.1
Version: 0.3.8.8b

**Comment by oitsjustjose** [comment]
Can confirm, deleting the `times` compound from `capabilities.dat > data > eidolon:reputation` was enough to fix this for us. Probably could use migration logic to fix this for others.

**Comment by euquinox** [comment]
have the same issue, had to downgrade to the old version

**Comment by Alexthw46** [comment]
managed to reproduce it by plugging in an old world data caps, trying to get what's wrong

**Comment by Alexthw46** [comment]
might have found the issue & fix, if it's not out tomorrow it will the day after

**Comment by Alexthw46** [comment]
updates on this? .9 is supposed to be fixing the issue

**Comment by KakashoLin** [comment]
> updates on this? .9 is supposed to be fixing the issue
Tested on the server that was having the kick issue, and this latest update fixed the issue.
