### ISSUE TITLE
Unlocking blood sign and sacrifice rite

### ISSUE THREAD

**Issue by ewsmith** [Alexthw46/Eidolon-Repraised#62]
I have performed the dark prayer over 100 times now and have not unlocked the animal sacrifice rite or the blood sign. is there some step other than just praying needed to unlock those?

edit: using straw effigy on a stone altar with wither rose, wither skull, and magic candle in holder. forgot to mention this earlier.

**Comment by ewsmith** [comment]
just looked through the changelogs and saw the `/devotion` command exists.
`/devotion me tryfix` did fix my issue.

**Comment by Alexthw46** [comment]
yeah sorry if i didn't answer first, that's the temporary workaround to a kind of bug as old as the mod. It's just that with the last update a typo in the code made the bug show consistently enough to finally track it down. Now i just need to experiment a fix...
