### ISSUE TITLE
Would it be possible to make SpellProjectileEntity extend the vanilla Projectile class?

### ISSUE THREAD

**Issue by Tavi007** [Alexthw46/Eidolon-Repraised#66]
Pretty much the title. 

I don't know if this change will break anything. I just hope, that it would be fast fix and easy to test.

The reason I'm asking this weird question is, that I wrote my own mod [ElementalCombat](https://www.curseforge.com/minecraft/mc-mods/elemental-combat) and that this change would allow my mod to interact with Eidolon without writing explizit code. Instead a simple datapack would be sufficient and in fact I already started to write [one](https://github.com/Tavi007/ElementalCombat-Datapacks/tree/main/Eidolon). (Please ignore the current versions of my mod. I've been working on the update for newer mc versions, but they are not ready yet...)

If it is to much work for you, that's fine by me. I just wanted to ask. (:

**Comment by Alexthw46** [comment]
Not sure why it wasn't a projectile subclass, likely legacy code. I didn't see issues with moving it, so 1.20 will have the swap
