### ISSUE TITLE
"Rendering screen" crash after looking at brazier recipes with JEI

### ISSUE THREAD

**Issue by mosharky** [Alexthw46/Eidolon-Repraised#7]
The crash happens with any brazier recipe, with the error: "java.lang.IllegalStateException: Not building!"

Eidolon: v0.3.5.3
Minecraft: v1.20.1
Forge: v47.2.1
Crash: https://mclo.gs/MoZeHwA

**Comment by Alexthw46** [comment]
Duplicate of #5 basically. Incompatibile with ImmediatelyFast until the bufferbuilder thing is sorted out.

**Comment by Alexthw46** [comment]
Duplicate of #5 basically. Incompatibile with ImmediatelyFast until the bufferbuilder thing is sorted out.

**Comment by mosharky** [comment]
ah sorry, i wasnt aware that mod was related to that crash
