### ISSUE TITLE
Soulfire Wand projectiles not affected by Archangel's Sight on players

### ISSUE THREAD

**Issue by TillRauch** [Alexthw46/Eidolon-Repraised#76]
Forge Version: 47.3.5
Eidolon : Repraised Version: 0.3.8.13

When having the Archangel's Sight Ring equipped (and configured to also target players) projectiles like arrows shot from a vanilla bow will be guided towards the nearest enemy player. However, the energy bolts shot from a Soulfire Wand will not target enemy players but instead fly straight ahead. 

This might be intentional but I assumed since the energy bolts do target mobs they should also target players.

**Comment by TillRauch** [comment]
After some digging in the code I believe this is due to this function 
https://github.com/Alexthw46/Eidolon-Repraised/blob/37484d80d90bba3cc7fc674b913d862fb40698b3/src/main/java/elucent/eidolon/common/entity/SpellProjectileEntity.java#L53
which gets used here
https://github.com/Alexthw46/Eidolon-Repraised/blob/37484d80d90bba3cc7fc674b913d862fb40698b3/src/main/java/elucent/eidolon/util/EntityUtil.java#L54
never returning true if `target` is a player. 

I am unsure how exactly to fix this. Might also be wrong in my understanding of the code.

**Comment by SiverDX** [comment]
add `minecraft:player` to https://github.com/Alexthw46/Eidolon-Repraised/blob/1.20.1-Neo/src/generated/resources/data/eidolon/tags/entity_types/trackable.json using a datapack

**Comment by TillRauch** [comment]
Yeah, that makes sense. Thanks
